baseURL = "https://remotecards.netlify.com/"
languageCode = "en-us"
title = "remote.cards"
description = "Generate a card to tell your audience what you’re up to."
theme="hello"

[params]
  description = "Generate a card to tell your audience what you’re up to."
  strapline = "Generate a card to tell your audience what you’re up to."
  location = "London, UK"

[permalinks]
  page = "/:title/"

[[menu.main]]
  name = "FAQs"
  url = "/#modal-faq"
  weight = 5

[[menu.main]]
  name = "Suggestions"
  url = "/#modal-suggestions"
  weight = 10
