baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "hello.cards"
description = "A simple hello card generator"
theme="hello"

[permalinks]
  page = "/:title/"

[[menu.main]]
  name = "FAQs"
  url = "/#modal-faq"
  weight = 5

[[menu.main]]
  name = "Suggestions"
  url = "/#modal-suggestions"
  weight = 10
