baseURL = "https://remotecards.netlify.app/"
languageCode = "en-us"
title = "remote.cards"
description = "Generate a card and tell your audience when you’re live. "
theme="hello"

[params]
  description = "Generate a card and tell your audience when you’re live. "
  strapline = "Generate a card and tell your audience when you’re live. "
  location = "London, UK"

[permalinks]
  page = "/:title/"

[[menu.main]]
  name = "FAQs"
  url = "/#modal-faq"
  weight = 5

[[menu.main]]
  name = "Suggestions"
  url = "/#modal-suggestions"
  weight = 10
